#!/bin/bash

# Generate docs/screens.md — a full gallery of every Paparazzi snapshot, grouped by screen.
# Paths are read from the actual snapshot files, so the gallery can never drift from reality.
#
# Two steps:
#   1) ./gradlew :app:recordPaparazziDebug             # (re)generate the PNGs
#   2) scripts/generate_screenshots_readme.sh          # rebuild this gallery

# Always run from project root (script lives in scripts/).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.." || exit 1

SNAPSHOTS_DIR="app/src/test/snapshots/images"
OUTPUT_FILE="docs/screens.md"
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Paparazzi names files like:
#   com.mk.androidshowcase.presentation.screen.calendar_CalendarScreenScreenshotTest_calendarScreen[0]_light.png
# The '[' and ']' must be percent-encoded in Markdown/HTML image src.
url_encode() { echo "$1" | sed 's/\[/%5B/g; s/\]/%5D/g'; }

{
    echo "# UI Screenshots"
    echo ""
    echo "Auto-generated from Paparazzi screenshot tests — do not edit by hand."
    echo "Regenerate with:"
    echo ""
    echo '```bash'
    echo "./gradlew :app:recordPaparazziDebug && scripts/generate_screenshots_readme.sh"
    echo '```'
    echo ""
} > "$OUTPUT_FILE"

prev_screen=""
for file in $(ls "$SNAPSHOTS_DIR"/*.png 2>/dev/null | sort); do
    filename=$(basename "$file")

    # Screen = the segment after '.screen.' and before the next '_'
    # (e.g. 'calendar' from ...screen.calendar_CalendarScreenScreenshotTest_...).
    screen_name=$(echo "$filename" | sed -E 's/.*\.screen\.([a-z0-9]+)_.*/\1/')
    # State label = everything after 'ScreenshotTest_' (e.g. 'calendarScreen[0]_light').
    state=$(echo "$filename" | sed -E 's/.*ScreenshotTest_//; s/\.png$//')
    rel_path="$(url_encode "../$SNAPSHOTS_DIR/$filename")"

    if [[ "$screen_name" != "$prev_screen" ]]; then
        [[ -n "$prev_screen" ]] && echo "" >> "$OUTPUT_FILE" && echo "" >> "$OUTPUT_FILE"
        title="$(tr '[:lower:]' '[:upper:]' <<< "${screen_name:0:1}")${screen_name:1}"
        {
            echo "## $title"
            echo ""
        } >> "$OUTPUT_FILE"
        prev_screen="$screen_name"
    fi

    echo -n "<img src=\"$rel_path\" width=\"200\" alt=\"$screen_name — $state\" /> " >> "$OUTPUT_FILE"
done

{
    echo ""
    echo ""
    echo "---"
    echo "*Generated by \`scripts/generate_screenshots_readme.sh\`*"
} >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
